'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SupraReports.Model.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT au.CDUSUARIO,
        '''  CASE
        '''    WHEN NU.cdusuario IS NULL
        '''    THEN 0
        '''    ELSE 1
        '''  END AS tienePermiso,
        '''  CASE
        '''    WHEN pu.swadmin IS NULL
        '''    THEN 0
        '''    ELSE pu.swadmin
        '''  END AS esAdmin
        '''FROM RMIS_ADMON.ADGE_USUARIOS au
        '''JOIN RMIS_ADMON.ADGE_ACCESOS_APLIC aa
        '''ON aa.CDUSUARIO = au.CDUSUARIO
        '''AND aa.CDAPLIC = &apos;NESS&apos;
        '''LEFT JOIN RMIS_ADMON.NECA_USUARIO nu
        '''ON nu.CDUSUARIO = au.CDUSUARIO
        '''LEFT JOIN RMIS_ADMON.NECA_PERMISO_USUARIO pu
        '''ON pu.CDUSUARIO = nu.CDUSUARIO
        '''AND pu.IDPROYECTO = :idProyecto;.
        '''</summary>
        Friend ReadOnly Property query_permisos_usuarios() As String
            Get
                Return ResourceManager.GetString("query_permisos_usuarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ueriskmi_sas() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ueriskmi_sas", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
