SELECT AU.CDUSUARIO as nombreUsuario,
  CASE
    WHEN PU.CDUSUARIO IS NULL
    THEN 0
    ELSE 1
  END AS tienePermiso,
  CASE
    WHEN PU.SWADMIN IS NULL
    THEN 0
    ELSE PU.SWADMIN
  END AS esAdministrador
FROM RMIS_ADMON.ADGE_USUARIOS AU
JOIN RMIS_ADMON.ADGE_ACCESOS_APLIC AA
  ON AA.CDUSUARIO = AU.CDUSUARIO
 AND AA.CDAPLIC = 'NESS'
LEFT JOIN RMIS_ADMON.NECA_USUARIO NU
  ON NU.CDUSUARIO = AU.CDUSUARIO
LEFT JOIN RMIS_ADMON.NECA_PERMISO_USUARIO PU
  ON PU.CDUSUARIO = NU.CDUSUARIO
 AND PU.IDPROYECTO = :idProyecto